# all : ClientWithoutSecurity.java ServerWithoutSecurity.java 
# 	javac ClientWithoutSecurity.java
# 	javac ServerWithoutSecurity.java

all : ClientCP1.java ServerCP1.java 
	javac ClientCP1.java
	javac ServerCP1.java

server : ServerCP1.class 
	java ServerCP1

client : ClientCP1.class 
	java ClientCP1 100.txt